import type { NamePack } from './packs.ts';

// The 24 letters in alphabet order, then archaic letters for the biggest games (SPEC §5).
export const greek: NamePack = {
  id: 'greek',
  label: 'Greek letters',
  names: [
    'Alpha',
    'Beta',
    'Gamma',
    'Delta',
    'Epsilon',
    'Zeta',
    'Eta',
    'Theta',
    'Iota',
    'Kappa',
    'Lambda',
    'Mu',
    'Nu',
    'Xi',
    'Omicron',
    'Pi',
    'Rho',
    'Sigma',
    'Tau',
    'Upsilon',
    'Phi',
    'Chi',
    'Psi',
    'Omega',
    'Digamma',
    'Koppa',
    'Sampi',
    'San',
    'Sho',
    'Yot',
  ],
};
